### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by mriedmann** [openshift/egress-router-cni#14]
Hi everyone!

I feel a bit stupid here, but I am really interested in this cni plugin and the egress router for OpenShift 4.x in general. Is there any documentation on how to install/use this plugin and also in what status (GA, tech preview, beta, alpha) this project is? I would absolutely appreciate any hint.

Thank you!

**Comment by danielmellado** [comment]
Hey @mriedmann , for now, you can abide to the enhancement proposal put to openshift [1]. Regarding the installation, there's a  PR to cluster network operator [2], who would just go and deploy this hooked up to multus' daemonset, so basically it'll copy the CNI binary to /opt/cni/bin.

Also, take into consideration that this CNI plugin is mostly intended for ovn-kubernetes, so if you're using openshift-sdn everything should still work as it was in 3.11.

Regarding the status, there's still steps to complete, but you'd at least should be able to go ahead and see the pod with the interfaces around, yet still the iptables integration work is still to be completed, so I'd call it beta ;)

[1] https://github.com/openshift/enhancements/blob/master/enhancements/network/egress-router.md
[2] https://github.com/openshift/cluster-network-operator/pull/815

**Comment by mriedmann** [comment]
Thank you very much! That is some very vital information.  

> Also, take into consideration that this CNI plugin is mostly intended for ovn-kubernetes

Didn't figured that, thx!

> so if you're using openshift-sdn everything should still work as it was in 3.11

Is there any official notice that the old egress router is fully supported on OCP 4.x? The documentation does not mention anything about the whole "egress router" topic so I assumed that it is not.

**Comment by danielmellado** [comment]
Hi @mriedmann, the documentation is ongoing, but I'll check with the doc team just to fully double-check. AFAIK it should just work. So, overall, the old egress router 'just works' on OCP 4.x, as long as you're using openshift-sdn. The reason for this, and without going to deep into technical questions, is that openshift sdn has a 'hack' to be able to get a macvlan interface with a label. We wouldn't like to keep that for ovn-k and thus we're using multus for it. Anyways, feel free to ping me if you need further information!

**Comment by danielmellado** [comment]
I added documentation for developers, so I'll be marking this as done :D
